# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class GUI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(945, 756)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_port = QtWidgets.QLabel(self.groupBox)
        self.label_port.setObjectName("label_port")
        self.horizontalLayout.addWidget(self.label_port)
        self.combo_port = QtWidgets.QComboBox(self.groupBox)
        self.combo_port.setObjectName("combo_port")
        self.horizontalLayout.addWidget(self.combo_port)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_baud = QtWidgets.QLabel(self.groupBox)
        self.label_baud.setObjectName("label_baud")
        self.horizontalLayout.addWidget(self.label_baud)
        self.combo_baud = QtWidgets.QComboBox(self.groupBox)
        self.combo_baud.setObjectName("combo_baud")
        self.horizontalLayout.addWidget(self.combo_baud)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_findport = QtWidgets.QPushButton(self.groupBox)
        self.button_findport.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_findport.setObjectName("button_findport")
        self.horizontalLayout_2.addWidget(self.button_findport)
        self.button_connect = QtWidgets.QPushButton(self.groupBox)
        self.button_connect.setObjectName("button_connect")
        self.horizontalLayout_2.addWidget(self.button_connect)
        self.button_disconnect = QtWidgets.QPushButton(self.groupBox)
        self.button_disconnect.setObjectName("button_disconnect")
        self.horizontalLayout_2.addWidget(self.button_disconnect)
        self.button_autoconnect = QtWidgets.QPushButton(self.groupBox)
        self.button_autoconnect.setObjectName("button_autoconnect")
        self.horizontalLayout_2.addWidget(self.button_autoconnect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_devmodel = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_devmodel.setPalette(palette)
        self.label_devmodel.setObjectName("label_devmodel")
        self.verticalLayout_3.addWidget(self.label_devmodel)
        self.label_manufacturer = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_manufacturer.setPalette(palette)
        self.label_manufacturer.setObjectName("label_manufacturer")
        self.verticalLayout_3.addWidget(self.label_manufacturer)
        self.label_devicestatus = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_devicestatus.setPalette(palette)
        self.label_devicestatus.setObjectName("label_devicestatus")
        self.verticalLayout_3.addWidget(self.label_devicestatus)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sms = QtWidgets.QWidget()
        self.tab_sms.setObjectName("tab_sms")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_sms)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_sms)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.sms_to = QtWidgets.QLineEdit(self.tab_sms)
        self.sms_to.setObjectName("sms_to")
        self.verticalLayout_6.addWidget(self.sms_to)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab_sms)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.sms_message = QtWidgets.QPlainTextEdit(self.tab_sms)
        self.sms_message.setObjectName("sms_message")
        self.verticalLayout_7.addWidget(self.sms_message)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sms_send = QtWidgets.QPushButton(self.tab_sms)
        self.sms_send.setObjectName("sms_send")
        self.horizontalLayout_6.addWidget(self.sms_send)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.sms_clear = QtWidgets.QPushButton(self.tab_sms)
        self.sms_clear.setObjectName("sms_clear")
        self.horizontalLayout_6.addWidget(self.sms_clear)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(28, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab_sms, "")
        self.tab_datacall = QtWidgets.QWidget()
        self.tab_datacall.setObjectName("tab_datacall")
        self.tabWidget.addTab(self.tab_datacall, "")
        self.tab_netselection = QtWidgets.QWidget()
        self.tab_netselection.setObjectName("tab_netselection")
        self.tabWidget.addTab(self.tab_netselection, "")
        self.tab_phonebook = QtWidgets.QWidget()
        self.tab_phonebook.setObjectName("tab_phonebook")
        self.tabWidget.addTab(self.tab_phonebook, "")
        self.tab_http = QtWidgets.QWidget()
        self.tab_http.setObjectName("tab_http")
        self.tabWidget.addTab(self.tab_http, "")
        self.tab_ftp = QtWidgets.QWidget()
        self.tab_ftp.setObjectName("tab_ftp")
        self.tabWidget.addTab(self.tab_ftp, "")
        self.tab_gps = QtWidgets.QWidget()
        self.tab_gps.setObjectName("tab_gps")
        self.tabWidget.addTab(self.tab_gps, "")
        self.tab_tcpudp = QtWidgets.QWidget()
        self.tab_tcpudp.setObjectName("tab_tcpudp")
        self.tabWidget.addTab(self.tab_tcpudp, "")
        self.tab_email = QtWidgets.QWidget()
        self.tab_email.setObjectName("tab_email")
        self.tabWidget.addTab(self.tab_email, "")
        self.tab_diagonostics = QtWidgets.QWidget()
        self.tab_diagonostics.setObjectName("tab_diagonostics")
        self.tabWidget.addTab(self.tab_diagonostics, "")
        self.tab_command = QtWidgets.QWidget()
        self.tab_command.setObjectName("tab_command")
        self.tabWidget.addTab(self.tab_command, "")
        self.tab_scriptmode = QtWidgets.QWidget()
        self.tab_scriptmode.setObjectName("tab_scriptmode")
        self.tabWidget.addTab(self.tab_scriptmode, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        spacerItem7 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GSM Module"))
        self.groupBox.setTitle(_translate("Dialog", "Port Configuration"))
        self.label_port.setText(_translate("Dialog", "Port"))
        self.label_baud.setText(_translate("Dialog", "Baud Rate"))
        self.button_findport.setText(_translate("Dialog", "Find Ports"))
        self.button_connect.setText(_translate("Dialog", "Connect"))
        self.button_disconnect.setText(_translate("Dialog", "Disconnect"))
        self.button_autoconnect.setText(_translate("Dialog", "AutoConnect"))
        self.groupBox_2.setTitle(_translate("Dialog", "Connection"))
        self.label_3.setText(_translate("Dialog", "Device Model"))
        self.label_4.setText(_translate("Dialog", "Manufacturer"))
        self.label_5.setText(_translate("Dialog", "Status"))
        self.label_devmodel.setText(_translate("Dialog", "N/A"))
        self.label_manufacturer.setText(_translate("Dialog", "N/A"))
        self.label_devicestatus.setText(_translate("Dialog", "Disconnected"))
        self.label_9.setText(_translate("Dialog", "To"))
        self.label_10.setText(_translate("Dialog", "Message"))
        self.sms_send.setText(_translate("Dialog", "Send"))
        self.sms_clear.setText(_translate("Dialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sms), _translate("Dialog", "SMS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_datacall), _translate("Dialog", "Data Call"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_netselection), _translate("Dialog", "Network Selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_phonebook), _translate("Dialog", "Phonebook"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_http), _translate("Dialog", "HTTP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ftp), _translate("Dialog", "FTP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gps), _translate("Dialog", "GPS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tcpudp), _translate("Dialog", "TCP/UDP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_email), _translate("Dialog", "Email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_diagonostics), _translate("Dialog", "Diagonostics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_command), _translate("Dialog", "Command Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scriptmode), _translate("Dialog", "Script Mode"))
        